### ISSUE TITLE
Wrong file size?

### ISSUE THREAD

**Issue by assafmo** [DCSO/bloom#4]
Hi.

When using `-n 10000000000 -p 0.0000000001` the file size should be around `55GB`, but in reality it is around `350MB`. I'm not using `--gzip`.

Am I missing something?

https://hur.st/bloomfilter?n=10000000000&p=0.0000000001

**Comment by adewes** [comment]
Ah that's actually an overflow error I think, good catch! We should probably extend that to int64 to be safe (though filters of that size quickly become unhandy), I'll fix it ASAP.

**Comment by assafmo** [comment]
Thanks. Why would you say filters of that size quickly become unhandy?

**Comment by adewes** [comment]
It depends how you use the tool: If you use the CLI client the loading time for a 55 GB file will be quite high (and will probably yield a memory exception on most systems), so it's not a use case that we had in mind with this (though it's probably doable). Why would you need such a low false-positive rate?

**Comment by assafmo** [comment]
The CLI loads everything to RAM? Maybe mmap the file...

Anyway my `n` is very high. If I drop `p` to 0.000001 it's big.

https://hur.st/bloomfilter?n=10000000000&p=0.000001

**Comment by adewes** [comment]
It's an interesting use case, I'll see what we can do to make the tool work better with filters of that size.

**Comment by assafmo** [comment]
A suggestion - always use mmap: https://github.com/axiak/pybloomfiltermmap :smile:

**Comment by adewes** [comment]
Cool, thanks for the link, I'll check this out! What's the advantage of mmap in this case? Do you dynamically write new entries to your Bloom filter or do you generate it once and then check the values? I imagine for the former case mmap could be interesting whereas for the latter it (in my understanding) wouldn't make a big difference (as the file gets loaded only once)?

**Comment by assafmo** [comment]
mmap doesn't load the file in memory, but gives you a memory address that reads and writes to it will read and write to the file. 

so basically you can operate on memory addresses and the os will write it to file.

**Comment by adewes** [comment]
Ah I see, sounds great!

**Comment by assafmo** [comment]
this'll be very efficient even on huge files and won't consume memory at all.

**Comment by adewes** [comment]
I just wonder about the performance as the bit access patterns are really distributed randomly in a Bloom filter, so the number of bytes we will need to load grows (almost) linearly with the number of checks we do. Hence not entirely sure if we should switch this on by default, as one large sequential read into memory might be more efficient than just reading the bytes we actually need, at least for small filters. Still a very good solution for extremely large filters though, so we could probably offer a switch to toggle the two modes.

**Comment by assafmo** [comment]
Yes, a CLI flag would be awesome!

**Comment by satta** [comment]
Do we want to make mmapped loading of on-disk filter files a feature request issue (or convert this into it)?

**Comment by satta** [comment]
The original issue seems to have been fixed via #8 so I'll close this.
